[versions]

jUnit = "5.12.0"
lombok = "1.18.36"
nexus-publish = "2.0.0"

[libraries]

jUnit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jUnit" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]

nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }